name: a2-docker-compose-smoke
title: InSpec Profile
maintainer: Chef Software, Inc.
copyright: Copyright (c) 2019-2025 Progress Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.
copyright_email: engineering@chef.io
license: All Rights Reserved
summary: Automate 2.0 Docker Compose smoke tests
version: 0.1.0
depends:
  - name: a2-api-smoke
    path: ../a2-api-smoke
